default:
  image: node:18

stages:
  - preflight
  - deploy
  - clean

cache:
  paths:
    - node_modules/
    - apps/web/.next/cache/
    - apps/og/.next/cache/
    - apps/invoice/.next/cache/

variables:
  API_RAILWAY_SERVICE_ID: 4a2a1bfb-e499-4c71-bf7f-d9ad47443c31
  CRON_RAILWAY_SERVICE_ID: 348ba788-3282-4f27-9967-ca04eea9ac4b
  OG_RAILWAY_SERVICE_ID: 76d31e4b-218d-4f82-974d-f2c8e91480e2

before_script:
  - npm install -g pnpm
  - pnpm install --frozen-lockfile

include:
  - local: ".gitlab/ci/typecheck.yml"
  - local: ".gitlab/ci/lint.yml"
  - local: ".gitlab/ci/prettier.yml"
  - local: ".gitlab/ci/build.yml"
  - local: ".gitlab/ci/test.yml"
  - local: ".gitlab/ci/migrate-db.yml"
  - local: ".gitlab/ci/deploy-api.yml"
  - local: ".gitlab/ci/deploy-cron.yml"
  - local: ".gitlab/ci/deploy-og.yml"
  - local: ".gitlab/ci/housekeep.yml"
  - local: ".gitlab/ci/clean-merged-branches.yml"
  - component: $CI_SERVER_FQDN/components/code-quality/code-quality@1.0.4
