default:
  interruptible: true
  image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g pnpm
  - pnpm install --frozen-lockfile

typecheck:
  stage: build
  script: pnpm typecheck

lint:
  stage: build
  script: pnpm lint

prettier:
  stage: build
  script: pnpm prettier

build:
  stage: build
  script: pnpm build

test:
  stage: build
  script:
    - pnpm build
    - pnpm test:dev

deploy-db:
  only:
    - main
  stage: deploy
  variables:
    DATABASE_URL: $MAINNET_DATABASE_URL
  script:
    - cd packages/db
    - pnpm prisma:migrate

deploy-api:
  only:
    - main
  image: docker:20.10.16
  stage: deploy
  before_script: []
  environment: production
  services:
    - docker:20.10.16-dind
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/api:latest
    DOCKERHUB_IMAGE_TAG: heyxyz/api:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/api/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG

deploy-cron:
  only:
    - main
  image: docker:20.10.16
  stage: deploy
  before_script: []
  environment: production
  services:
    - docker:20.10.16-dind
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/cron:latest
    DOCKERHUB_IMAGE_TAG: heyxyz/cron:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/cron/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker tag $GITLAB_IMAGE_TAG $DOCKERHUB_IMAGE_TAG
    - docker push $DOCKERHUB_IMAGE_TAG

deploy-og:
  only:
    - main
  image: docker:20.10.16
  stage: deploy
  before_script: []
  environment: production
  services:
    - docker:20.10.16-dind
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/og:latest
    DOCKERHUB_IMAGE_TAG: heyxyz/og:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/og/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG
