default:
  interruptible: true
  image: node:18

stages:
  - deploy
  - build

cache:
  paths:
    - node_modules/

variables:
  API_RAILWAY_SERVICE_ID: 4a2a1bfb-e499-4c71-bf7f-d9ad47443c31
  CRON_RAILWAY_SERVICE_ID: 348ba788-3282-4f27-9967-ca04eea9ac4b
  OG_RAILWAY_SERVICE_ID: 76d31e4b-218d-4f82-974d-f2c8e91480e2

before_script:
  - npm install -g pnpm
  - pnpm install --frozen-lockfile

include:
  - local: ".gitlab/ci/typecheck.yml"

lint:
  stage: build
  script: pnpm lint

prettier:
  stage: build
  script: pnpm prettier

build:
  stage: build
  script: pnpm build

test:
  stage: build
  script:
    - pnpm build
    - pnpm test:dev

deploy-db:
  only:
    - main
  stage: deploy
  variables:
    DATABASE_URL: $MAINNET_DATABASE_URL
  script:
    - cd packages/db
    - pnpm prisma:migrate

deploy-api:
  only:
    - main
  image: docker:20.10.16
  stage: deploy
  before_script: []
  environment: production
  services:
    - docker:20.10.16-dind
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/api:latest
    DOCKERHUB_IMAGE_TAG: heyxyz/api:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/api/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker tag $GITLAB_IMAGE_TAG $DOCKERHUB_IMAGE_TAG
    - docker push $DOCKERHUB_IMAGE_TAG
    - curl https://redeploy.heyxyz.workers.dev?secret=$SECRET&service=$API_RAILWAY_SERVICE_ID

deploy-cron:
  only:
    - main
  image: docker:20.10.16
  stage: deploy
  before_script: []
  environment: production
  services:
    - docker:20.10.16-dind
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/cron:latest
    DOCKERHUB_IMAGE_TAG: heyxyz/cron:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/cron/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker tag $GITLAB_IMAGE_TAG $DOCKERHUB_IMAGE_TAG
    - docker push $DOCKERHUB_IMAGE_TAG
    - curl https://redeploy.heyxyz.workers.dev?secret=$SECRET&service=$CRON_RAILWAY_SERVICE_ID

deploy-og:
  only:
    - main
  image: docker:20.10.16
  stage: deploy
  before_script: []
  environment: production
  services:
    - docker:20.10.16-dind
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/og:latest
    DOCKERHUB_IMAGE_TAG: heyxyz/og:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/og/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - docker tag $GITLAB_IMAGE_TAG $DOCKERHUB_IMAGE_TAG
    - docker push $DOCKERHUB_IMAGE_TAG
    - curl https://redeploy.heyxyz.workers.dev?secret=$SECRET&service=$OG_RAILWAY_SERVICE_ID
