Deploy Cron:
  only:
    refs:
      - main
    changes:
      - apps/cron/**/*
      - packages/**/*
  needs: []
  environment: production
  stage: deploy
  image: docker:27.2.0
  services:
    - docker:27.2.0-dind
  before_script:
    - apk add --no-cache curl
  variables:
    GITLAB_IMAGE_TAG: $CI_REGISTRY/yo/hey/cron:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $GITLAB_IMAGE_TAG -f ./apps/cron/Dockerfile .
    - docker push $GITLAB_IMAGE_TAG
    - curl -s "https://redeploy.heyxyz.workers.dev?secret=$SECRET&service=$CRON_RAILWAY_SERVICE_ID"
